/**
 * @File Name          : CacheException.cls
 * @Description        : Exception class, useful for errors tied to caches
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/27/2020, 5:13:46 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/27/2020   Thomas Wilkins     Initial Version
**/
public inherited sharing class CacheException extends Exception {}
