/**
 * @File Name          : IQueryOptionsBuilder.cls
 * @Description        : Builder interface for building query options
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 5/2/2020, 7:44:55 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/25/2020   Thomas Wilkins     Initial Version
**/
public interface IQueryOptionsBuilder {
    IQueryOptions getQueryOptions();
}
