/**
 * @File Name          : SoqlException.cls
 * @Description        : Exception classs thrown when issues arise during soql queries
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 5/2/2020, 12:22:40 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    5/2/2020   Thomas Wilkins     Initial Version
**/
public inherited sharing class SoqlException extends Exception {}
