/**
 * @File Name          : TriggerDispatcherException.cls
 * @Description        : Exception thrown from trigger disaptcher issues
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/22/2020, 11:34:25 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/22/2020   Thomas Wilkins     Initial Version
**/
public inherited sharing class TriggerDispatcherException extends Exception {}
